app/register/forms.py
#!flask/bin/python
# encoding: utf-8
from flask_wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField, SelectField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo
from wtforms import ValidationError
from ..models import User


class RegistrationForm(Form):
    email = StringField('Email', validators=[DataRequired()])
    name = StringField('Name', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    #  password2 = PasswordField('Confirm password', validators=[DataRequired()])
    # def validate_email(self, field):
    #     if User.query.filter_by(email=field.data).first():
    #         raise ValidationError(u'该邮箱已经注册')
    #
    # def validate_name(self, field):
    #     if User.query.filter_by(name=field.data).first():
    #         raise ValidationError(u'该用户名已存在')

app/register/__init__.py
#!flask/bin/python
# encoding: utf-8
from flask import Blueprint


register = Blueprint('register', __name__)

from . import views

app/register/views.py
#!flask/bin/python
# encoding: utf-8

from app.register import register
from app.register.forms import RegistrationForm
from ..models import User
from flask import redirect, url_for, flash, render_template, Flask, request, current_app
from app import db
from flask_login import current_user
from flask_login import login_required
from threading import Thread
from flask_mail import Message
from app import mail
from flask_login import login_user
from flask_wtf.csrf import CsrfProtect
from .. import SQLAlchemy


def send_async_email(app, msg):
    with app.app_context():
        mail.send(msg)


def send_email(to, subject, template, **kwargs):
    app = current_app._get_current_object()
    msg = Message(app.config['FLASKY_MAIL_SUBJECT_PREFIX'] + subject,
                  sender=app.config['FLASKY_MAIL_SENDER'], recipients=[to])
    msg.body = render_template(template + '.txt', **kwargs)
    msg.html = render_template(template + '.html', **kwargs)
    thr = Thread(target=send_async_email, args=[app, msg])
    thr.start()
    return thr


csrf = CsrfProtect(current_app)


@csrf.exempt
@register.route('/user_register', methods=['GET', 'POST'])
def user_register():
    form = RegistrationForm()
    # a = User(name="aaa",
    #          email="aaa",
    #          password="aaa")
    # db.session.add(a)
    # db.session.commit()
    if form.validate_on_submit():
        user = User(name=form.name.data,
                    email=form.email.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        return render_template('src/views/weibo.html')
        # email_url = 'http://mail.' + form.email.data.split('@', 1)[-1]
        # token = user.generate_confirmation_token()
        # try:
        #     send_email(user.email, 'Confirm Your Account',
        #                'register/email/confirm', user=user, token=token)
        #     flash('A confirmation email has been sent to you by email.')
        #     return render_template('login/unconfirmed.html', user=user, email_url=email_url)
        # except:
        #     flash('Email sending failed and the  email is wrong')
        #     return render_template('login/unconfirmed.html', user=user, email_url=email_url)
        #     return render_template('src/view/main.html', user=user, email_url=email_url)
    return render_template('src/views/register.html', form=form)


@register.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.is_anonymous:
        flash(u'请先登录再验证')
        return redirect(url_for('login.user_login'))
    if current_user.confirm(token):
        flash('You have confirmed your account. Thanks!')
    else:
        flash('The confirmation link is invalid or has expired.')
        return redirect(url_for('register.resend_confirmation'))
    return redirect(url_for('admin.homepage'))


@register.route('/confirm')
@login_required
def resend_confirmation():
    token = current_user.generate_confirmation_token()
    if not send_email(current_user, 'register/email/confirm',
                      'Confirm Your Account', user=current_user, token=token):
        flash('Email sending failed')
    else:
        flash('A new confirmation email has been sent to you by email.')
    return redirect(url_for('login.user_login'))

app/templates/src/views/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>微博-不一样的人生</title>
    <link rel="icon" href="static/public/imgs/favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" href="static/public/imgs/favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" type="text/css" href="static/public/css/font-awesome.min.css">
    <style>
        * {
            margin: 0;
            padding: 0;
        }
    </style>

</head>
<body>

<div id="app">
    <weibo></weibo>
</div>


<script type="text/javascript" src="static/dist/index.bundle.js"></script>

</body>
</html>

app/templates/src/views/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>微博主页</title>
    <link rel="icon" href="../static/public/imgs/favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" href="../static/public/imgs/favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" type="text/css" href="../static/public/css/font-awesome.min.css">
    <style>
        * {
            padding: 0;
            margin: 0;
        }
    </style>
</head>
<body>

<div id="app">
    <m-weibo></m-weibo>
</div>

<script type="text/javascript" src="../static/dist/main.bundle.js"></script>
</body>
</html>

app/templates/src/views/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        #register {
            display: block;
            position: absolute;
            width: 600px;
            height: 400px;
            top: 50%;
            left: 50%;
            margin-top: -200px;
            margin-left: -300px;
            background-color: #fff;
            border-radius: 4px;
            box-shadow: 4px 4px 5px #ccc;
        }

        .register-info {
            width: 324px;
            height: 30px;
            margin: 30px auto;
            padding-bottom: 10px;
            text-align: center;
            border-bottom: 3px solid #f7691d
        }

        .register-info span {
            line-height: 30px;
        }

        .wr-register {
            width: 324px;
            height: 170px;
            margin: 20px auto 0;
            overflow: hidden;
        }

        .wr-register input {
            width: 300px;
            height: 20px;
            padding: 5px 10px;
            outline: none;
            border-radius: 5px;
            border: 1px solid #ccc;
            margin: 10px auto 0;
        }

        .wr-register input:focus {
            border-color: #eb7350;
        }

        .submit-register {
            width: 324px;
            height: 30px;
            font-size: 14px;
            background-color: #ff8140;
            border-radius: 5px;
            margin: 10px auto;
            text-align: center;
            cursor: pointer;
        }

        .submit-register a {
            display: block;
            text-decoration: none;
            width: 324px;
            height: 30px;
            color: #ffffff;
            line-height: 30px;
            background-color: #ff8140;
        }

        #error-msg {
            display: none;
            width: 100%;
            height: 30px;
            line-height: 30px;
            text-align: center;
            color: red;
        }
    </style>
</head>
<body style=" background-color: #d4d5e0;background-image: url(static/public/imgs/body_bg.jpg);background-repeat: repeat-x;background-position: center 0;">
<div id="register">
    <form class="register-box" method="POST" action="{{url_for('register.user_register')}}">
        <div class="register-info">
            <span>用户注册</span>
        </div>
        <div class="wr-register">
            <input id="name" type="text" name="name" placeholder="请输入用户名">
            <input id="email" type="email" name="email" placeholder="请输入注册邮箱">
            <input id="password" type="password" name="password" placeholder="请输入密码">
            <input id="re-password" type="password" name="password2" placeholder="请再一次输入密码">
        </div>

        <div id="error-msg">
        </div>
        <div class="submit-register">
            <a onclick="judgePassword()">
                <span>注册</span>
            </a>
        </div>
    </form>
</div>

<script type="text/javascript" src="static/public/js/axios.min.js"></script>
<script type="text/javascript">

    function judgePassword() {
        console.log("effect");
        var name = document.getElementById('name').value;
        console.log(name);
        var email = document.getElementById('email').value;
        var password = document.getElementById('password').value;
        var rePassword = document.getElementById('re-password').value;
        if (name == '' || email == '' || password == '' || rePassword == '') {
            document.getElementById('error-msg').innerHTML = "请补全信息";
            document.getElementById('error-msg').style.display = 'block';
        }
        else {
            if (password == rePassword) {
                axios.post('/user_register', {
                    name: name,
                    email: email,
                    password: password
                }).then(function (response) {
                    window.location.href = '/';
                }).catch(function (error) {
                    console.log(error);
                });
            }
            else {
                document.getElementById('error-msg').innerHTML = "两次输入密码不一样，请重新输入";
                document.getElementById('error-msg').style.display = 'block';
            }
        }


    }

</script>
</body>
</html>

app/templates/src/views/weibo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>微博-享受人生</title>
    <link rel="icon" href="static/public/imgs/favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" href="static/public/imgs/favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" type="text/css" href="static/public/css/font-awesome.min.css">
    <style>
        *{
            padding: 0;
            margin: 0;
        }
    </style>
</head>
<body>

    <div id="app">
        <u-weibo></u-weibo>
    </div>

<script type="text/javascript" src="static/dist/weibo.bundle.js"></script>
</body>
</html>